### ISSUE TITLE
Can I use this package to convert my intel hex to binary by putting the start and end addresses?

### ISSUE THREAD

**Issue by XisoDev** [domohuhn/intel_hex#1]
I have an intel hex file.
I need to binary this.
Can I use this package to convert my intel hex to binary by putting the start and end addresses?

**Comment by domohuhn** [comment]
Yes, you can use this package to convert an intel hex to binary. I have added an example showing how you can do that:

https://github.com/domohuhn/intel_hex/blob/main/example/convert_to_binary.dart

The example will pad the file with zeros if there are gaps in the hex file (especially the start would be padded with zeros), but you can also just write the individual segments to disk.

Closing this issue.
